import 'symbol.dart';
import 'unit_expr_problem.dart';

// 原子物理の問題（expr単位で集約・category/defs内包）
final atomExprProblems = <UnitExprProblem>[
  UnitExprProblem(
    expr: "R",
    meaning: "リュードベリ定数",
    meaningEn: "Rydberg constant",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "R",
        nameJa: "リュードベリ定数",
        meaning: "リュードベリ定数の比例係数",
        unitSymbol: "m^-1",
        baseUnits: "m^-1",
        dimension: "L^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "4EDF2C29-71D8-4C85-8C2B-33DFC17E4595",
        answer: "m^-1",
        units: ["m", "kg", "s", "A", "m^-1", "kg^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "h",
    meaning: "プランク定数",
    meaningEn: "Planck constant",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "900ABFA8-2DB8-48FF-8F8B-3B96A9515A8A",
        answer: "J s",
        units: ["J", "m", "s", "A", "J^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "W",
    meaning: "仕事関数",
    meaningEn: "Work function",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "W",
        nameJa: "仕事関数",
        meaning: "光電効果で金属から電子を取り出すのに必要な最小のエネルギー",
        nameEn: "Work function",
        meaningEn: "Minimum energy required to remove an electron from a metal (photoelectric effect)",
        unitSymbol: "J",
        baseUnits: "kg·m^2·s^-2",
        dimension: "ML^2T^-2",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "2E369193-B9E1-4613-BEF7-9ECED07ED5CA",
        shortExplanation: r"W\text{はエネルギー。}",
        shortExplanationEn: r"W\text{ is energy.}",
        answer: "J",
        units: ["kg", "J", "W", "m^-1", "s^-1", "Pa", "N"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "e",
    meaning: "電気素量",
    meaningEn: "Elementary charge",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "e",
        nameJa: "電気素量",
        meaning: "電子の電荷の大きさ",
        nameEn: "Elementary charge",
        meaningEn: "Magnitude of the electron charge",
        unitSymbol: "C",
        baseUnits: "A·s",
        dimension: "TI",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "BA69A6E9-D603-4444-8636-3CA149FFA137",
        shortExplanation: r"e\text{は電荷。}",
        shortExplanationEn: r"e\text{ is electric charge.}",
        answer: "C",
        units: ["C", "s^-1", "Ω", "A", "V", "m^-1", "J"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "1eV",
    meaning: "電子ボルト",
    meaningEn: "Electron volt",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "eV",
        nameJa: "電子ボルト",
        meaning: "1電子ボルトのエネルギー",
        nameEn: "electron volt",
        meaningEn: "Energy of one electron volt",
        unitSymbol: "J",
        baseUnits: "kg·m^2·s^-2",
        dimension: "ML^2T^-2",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "F8624EAC-1D57-4934-9364-AA836D00EF84",
        shortExplanation: r"1eV\text{はエネルギー。}",
        shortExplanationEn: r"1eV\text{ is energy.}",
        answer: "J",
        units: ["kg", "J", "W", "m^-1", "s^-1", "Pa", "N"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "1u",
    meaning: "原子質量単位",
    meaningEn: "Atomic mass unit",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "u",
        nameJa: "原子質量単位",
        meaning: "原子質量の単位",
        nameEn: "atomic mass unit",
        meaningEn: "Unit of atomic mass",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "97E888E6-AACB-4D3D-B9AD-7FCE5D333938",
        shortExplanation: r"1u\text{は質量。}",
        shortExplanationEn: r"1u\text{ is mass.}",
        answer: "kg",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "hcR",
    meaning: "水素原子のイオン化エネルギー",
    meaningEn: "Hydrogen ionization energy",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        nameEn: "Planck constant",
        meaningEn: "Planck constant",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光速",
        nameEn: "Speed of light",
        meaningEn: "Speed of light",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
      SymbolDef(
        symbol: "R",
        nameJa: "リュードベリ定数",
        meaning: "リュードベリ定数の比例係数",
        nameEn: "Rydberg constant",
        meaningEn: "Proportionality constant in the Rydberg formula",
        unitSymbol: "m^-1",
        baseUnits: "m^-1",
        dimension: "L^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "EAF72113-C43C-409D-B7AC-791EA92F97F3",
        shortExplanation: r"hcR\text{はエネルギー。}",
        shortExplanationEn: r"hcR\text{ is energy.}",
        answer: "J",
        units: ["kg", "J", "W", "m^-1", "s^-1", "Pa", "N"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "mc^2",
    meaning: "静止エネルギー",
    meaningEn: "Rest energy",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "m",
        nameJa: "質量",
        meaning: "物体の質量",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光速",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "418F761C-8E7F-4062-BD35-E9EBFBA76B56",
        shortExplanation: r"mc^2\text{は静止エネルギー。}",
        shortExplanationEn: r"mc^2\text{ is rest energy.}",
        answer: "J",
        units: ["N", "W", "J", "kg", "m^-1", "s^-1", "kg^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"h\nu",
    meaning: "光子のエネルギー",
    meaningEn: "Photon energy",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: r"\nu",
        nameJa: "振動数",
        meaning: "光の振動数",
        unitSymbol: "Hz",
        baseUnits: "s^-1",
        dimension: "T^-1",
        texSymbol: r"\nu",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "0070DEF6-6EBC-40C0-8B07-1D9E0F2DF54A",
        shortExplanation: r"h\nu\text{は光子のエネルギー。}",
        shortExplanationEn: r"h\nu\text{ is photon energy.}",
        answer: "kg m^2 s^-2",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{hc}{\lambda}",
    meaning: "光子のエネルギー",
    meaningEn: "Photon energy",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光速",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
      SymbolDef(
        symbol: "λ",
        nameJa: "波長",
        meaning: "光の波長",
        meaningEn: "Wavelength of light",
        unitSymbol: "m",
        baseUnits: "m",
        dimension: "L",
        texSymbol: r"\lambda",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "3688B726-C19A-4840-8FE4-EE0F7B9DD163",
        shortExplanation: r"\frac{hc}{\lambda}\text{は光子のエネルギー。}",
        shortExplanationEn: r"\frac{hc}{\lambda}\text{ is photon energy.}",
        answer: "kg m^2 s^-2",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{hc}{eV}",
    meaning: "光子の波長",
    meaningEn: "Photon wavelength",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光速",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
      SymbolDef(
        symbol: "eV",
        nameJa: "電子ボルト",
        meaning: "1電子ボルトのエネルギー",
        nameEn: "electron volt",
        meaningEn: "Energy of one electron volt",
        unitSymbol: "eV",
        baseUnits: "kg·m^2·s^-2",
        dimension: "ML^2T^-2",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "9C53A75B-E129-4BB9-91C5-63BCF86F4E68",
        shortExplanation: r"\frac{hc}{eV}\text{は光子の波長。}",
        shortExplanationEn: r"\frac{hc}{eV}\text{ is photon wavelength.}",
        answer: "m",
        units: ["kg", "m", "s", "A", "kg^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{h}{mc}",
    meaning: "コンプトン波長",
    meaningEn: "Compton wavelength",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "m",
        nameJa: "質量",
        meaning: "物体の質量",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光速",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "061FAD3B-42AF-4DF8-B5D5-32A18AF3083E",
        shortExplanation: r"\frac{h}{mc}\text{はコンプトン波長。}",
        shortExplanationEn: r"\frac{h}{mc}\text{ is Compton wavelength.}",
        answer: "m",
        units: ["kg", "m", "s", "A", "kg^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{\epsilon_0 h^2}{\pi m e^2}",
    meaning: "ボーア半径",
    meaningEn: "Bohr radius",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "ε0",
        nameJa: "真空の誘電率",
        meaning: "誘電率",
        unitSymbol: "F/m",
        baseUnits: "kg^-1·m^-3·s^4·A^2",
        dimension: "M^-1L^-3T^4I^2",
        texSymbol: r"\epsilon_{0}",
      ),
      SymbolDef(
        symbol: "m",
        nameJa: "質量",
        meaning: "電子の質量",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
      SymbolDef(
        symbol: "e",
        nameJa: "電気素量",
        meaning: "電子の電荷の大きさ",
        unitSymbol: "C",
        baseUnits: "A·s",
        dimension: "TI",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "11C65A30-EC80-42E0-AE01-F5B8B174595E",
        shortExplanation: r"\frac{\epsilon_0 h^2}{\pi m e^2}\text{はボーア半径。}",
        shortExplanationEn: r"\frac{\epsilon_0 h^2}{\pi m e^2}\text{ is Bohr radius.}",
        answer: "m",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{m e^4}{8 \epsilon_0^2 h^2}",
    meaning: "水素原子のイオン化エネルギー",
    meaningEn: "Hydrogen ionization energy",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "m",
        nameJa: "質量",
        meaning: "電子の質量",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
      SymbolDef(
        symbol: "e",
        nameJa: "電気素量",
        meaning: "電子の電荷の大きさ",
        unitSymbol: "C",
        baseUnits: "A·s",
        dimension: "TI",
      ),
      SymbolDef(
        symbol: "ε0",
        nameJa: "真空の誘電率",
        meaning: "誘電率",
        unitSymbol: "F/m",
        baseUnits: "kg^-1·m^-3·s^4·A^2",
        dimension: "M^-1L^-3T^4I^2",
        texSymbol: r"\epsilon_{0}",
      ),
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "DFF6CD4A-C313-4B04-A11D-08AF0EBED755",
        shortExplanation: r"\frac{m e^4}{8 \epsilon_0^2 h^2}\text{は水素原子のイオン化エネルギー。}",
        shortExplanationEn: r"\frac{m e^4}{8 \epsilon_0^2 h^2}\text{ is hydrogen ionization energy.}",
        answer: "kg m^2 s^-2",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{h}{\lambda}",
    meaning: "光の運動量",
    meaningEn: "Momentum of light",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "λ",
        nameJa: "波長",
        meaning: "光の波長",
        unitSymbol: "m",
        baseUnits: "m",
        dimension: "L",
        texSymbol: r"\lambda",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "33598EBE-4000-4F53-9459-87BD88BD8B13",
        shortExplanation: r"\frac{h}{\lambda}\text{は光の運動量。}",
        shortExplanationEn: r"\frac{h}{\lambda}\text{ is momentum of light.}",
        answer: "N s",
        units: ["m", "kg", "s", "N", "Pa^-1", "J"],
      ),
      UnitProblem(
        id: "4F912206-A3A4-40EB-9A59-E37A788E5161",
        shortExplanation: r"\frac{h}{\lambda}\text{は光の運動量。}",
        shortExplanationEn: r"\frac{h}{\lambda}\text{ is momentum of light.}",
        answer: "kg m s^-1",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{h\nu}{c}",
    meaning: "光の運動量",
    meaningEn: "Momentum of light",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: r"\nu",
        nameJa: "振動数",
        meaning: "光の振動数",
        unitSymbol: "Hz",
        baseUnits: "s^-1",
        dimension: "T^-1",
        texSymbol: r"\nu",
      ),
      SymbolDef(
        symbol: "c",
        nameJa: "光速",
        meaning: "光の伝播速度",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "B71A1757-D5D3-4BAA-BC16-46D095DF2B63",
        shortExplanation: r"\frac{h\nu}{c}\text{は光の運動量。}",
        shortExplanationEn: r"\frac{h\nu}{c}\text{ is momentum of light.}",
        answer: "kg m s^-1",
        units: ["kg", "m", "s", "A", "kg^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{h}{p}",
    meaning: "ドブロイ波長",
    meaningEn: "de Broglie wavelength",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "p",
        nameJa: "運動量",
        meaning: "物体の運動量",
        unitSymbol: "kg·m/s",
        baseUnits: "kg·m·s^-1",
        dimension: "MLT^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "FF616BE8-3890-47A0-BAAF-98C5AE7FDF29",
        shortExplanation: r"\frac{h}{p}\text{はドブロイ波長。}",
        shortExplanationEn: r"\frac{h}{p}\text{ is de Broglie wavelength.}",
        answer: "m",
        units: ["kg", "m", "s", "A", "kg^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"\frac{h}{mv}",
    meaning: "ドブロイ波長",
    meaningEn: "de Broglie wavelength",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "h",
        nameJa: "プランク定数",
        meaning: "プランク定数",
        unitSymbol: "J·s",
        baseUnits: "kg·m^2·s^-1",
        dimension: "ML^2T^-1",
      ),
      SymbolDef(
        symbol: "m",
        nameJa: "質量",
        meaning: "物体の質量",
        unitSymbol: "kg",
        baseUnits: "kg",
        dimension: "M",
      ),
      SymbolDef(
        symbol: "v",
        nameJa: "速度",
        meaning: "物体の速度",
        unitSymbol: "m/s",
        baseUnits: "m·s^-1",
        dimension: "LT^-1",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "00554974-4F49-4601-B72B-971F880275C0",
        shortExplanation: r"\frac{h}{mv}\text{はドブロイ波長。}",
        shortExplanationEn: r"\frac{h}{mv}\text{ is de Broglie wavelength.}",
        answer: "m",
        units: ["kg", "m", "s", "A", "kg^-1", "m^-1", "s^-1", "A^-1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: r"2d \sin \theta",
    meaning: "ブラッグの条件の光路差",
    meaningEn: "Optical path difference (Bragg condition)",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "d",
        nameJa: "面間隔",
        meaning: "結晶の格子面間隔",
        nameEn: "Interplanar spacing",
        meaningEn: "Interplanar spacing in a crystal",
        unitSymbol: "m",
        baseUnits: "m",
        dimension: "L",
      ),
      SymbolDef(
        symbol: "θ",
        nameJa: "ブラッグ角",
        meaning: "入射線と格子面のなす角",
        nameEn: "Bragg angle",
        meaningEn: "Angle between incident beam and lattice plane",
        unitSymbol: "rad",
        baseUnits: "1",
        dimension: "1",
        texSymbol: r"\theta",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "7420D5EE-6115-4251-8D78-1773B5BF3A98",
        shortExplanation: r"2d\sin\theta\text{は光路差（長さ）。}",
        shortExplanationEn: r"2d\sin\theta\text{ is a length (optical path difference).}",
        answer: "m",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "γ",
    meaning: "ローレンツ因子",
    meaningEn: "Lorentz factor",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "γ",
        nameJa: "ローレンツ因子",
        meaning: "相対論のガンマ因子",
        nameEn: "Lorentz factor",
        meaningEn: "Relativistic gamma factor",
        unitSymbol: "無次元",
        baseUnits: "1",
        dimension: "無次元",
        texSymbol: r"\gamma",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "BF3253AB-37BB-414A-8631-B75760BE931B",
        answer: "無次元",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
  UnitExprProblem(
    expr: "β",
    meaning: "ベータ因子",
    meaningEn: "beta factor",
    category: UnitCategory.atom,
    defs: [
      SymbolDef(
        symbol: "β",
        nameJa: "ベータ因子",
        meaning: "相対論のベータ因子",
        nameEn: "Beta factor",
        meaningEn: "Relativistic beta factor",
        unitSymbol: "無次元",
        baseUnits: "1",
        dimension: "無次元",
        texSymbol: r"\beta",
      ),
    ],
    unitProblems: [
      UnitProblem(
        id: "5ADDA26C-7C93-49D2-8A95-26CBC07AAD2E",
        answer: "無次元",
        units: ["m", "m^-1", "s", "s^-1", "kg", "kg^-1", "1"],
      ),
    ],
  ),
];

