// tool/generate_problem_access_map.dart
//
// Generates `lib/services/payment/problem_access_map.dart`.
//
// Usage:
//   dart run tool/generate_problem_access_map.dart > lib/services/payment/problem_access_map.dart
//
// Notes:
// - This is a pure Dart tool (no Flutter imports).
// - The access map is an explicit flag table: expr|meaning -> requiredProductId.
// - Unlisted keys are treated as FREE by default (safer during iteration).

import 'dart:io';

import '../lib/problems/unit/problems.dart' show unitExprProblems;
import '../lib/problems/unit/symbol.dart' show UnitCategory;
import '../lib/problems/unit/unit_expr_problem.dart' show UnitExprProblem;

// --- Product IDs (placeholders; swap later if needed) ---
const String mechanicsUnlockProductId = 'mechanics_all_unlock';
const String emUnlockProductId = 'electromagnetism_all_unlock';

// --- Free boundaries (inclusive) ---
// Mechanics: free through energy unit; paid from momentum onward => rank >= 400.
const int mechanicsPaidFromRankInclusive = 400; // 'mv|運動量'
// Electromagnetism: free through Q^2/2C; paid after it => rank > 250.
const int emPaidAfterRank = 250; // r'\frac{Q^2}{2C}|静電エネルギー'

String exprKey(UnitExprProblem ep) => '${ep.expr}|${ep.meaning ?? ''}';

String _normalizedExprForRank(UnitExprProblem ep) {
  // Some problems use Unicode symbols while the curriculum rank tables use TeX-ish tokens.
  // Normalize only for ranking (the access map keys still use the original expr|meaning).
  var expr = ep.expr;
  // μ (unicode) -> \mu (rank table uses \mu)
  expr = expr.replaceAll('μ', r'\mu');
  return expr;
}

int _rank(UnitExprProblem ep) {
  final k = '${_normalizedExprForRank(ep)}|${ep.meaning ?? ''}';
  switch (ep.category) {
    case UnitCategory.mechanics:
      return _mechanicsCurriculumRank[k] ?? 9999;
    case UnitCategory.electromagnetism:
      return _emCurriculumRank[k] ?? 9999;
    case UnitCategory.waves:
    case UnitCategory.thermodynamics:
    case UnitCategory.atom:
      return 0;
  }
}

String? requiredProductIdFor(UnitExprProblem ep) {
  final r = _rank(ep);
  if (ep.category == UnitCategory.mechanics) {
    // Paid from momentum onward.
    return (r >= mechanicsPaidFromRankInclusive)
        ? mechanicsUnlockProductId
        : null;
  }
  if (ep.category == UnitCategory.electromagnetism) {
    // Paid after capacitor-energy block.
    return (r > emPaidAfterRank) ? emUnlockProductId : null;
  }
  return null;
}

void main() {
  // Generate entries (deterministic order by exprKey for stable diffs).
  final entries = <String, String>{};

  // Diagnostics: detect missing ranks in gated categories.
  final missingRank = <String>[];

  for (final ep in unitExprProblems) {
    final k = exprKey(ep);
    final required = requiredProductIdFor(ep);

    if ((ep.category == UnitCategory.mechanics ||
            ep.category == UnitCategory.electromagnetism) &&
        _rank(ep) == 9999) {
      missingRank.add(k);
    }

    if (required != null) {
      entries[k] = required;
    }
  }

  final sortedKeys = entries.keys.toList()..sort();

  // Header / imports
  stdout.writeln('// GENERATED FILE. DO NOT EDIT BY HAND.');
  stdout.writeln('// Generated by: tool/generate_problem_access_map.dart');
  stdout.writeln('//');
  stdout.writeln('// Map: expr|meaning -> requiredProductId');
  stdout.writeln('// Unlisted keys are treated as FREE by default.');
  stdout.writeln();
  stdout.writeln(
    "import '../../problems/unit/unit_expr_problem.dart' show UnitExprProblem;",
  );
  stdout.writeln();
  stdout.writeln(
    "String exprKey(UnitExprProblem ep) => '\${ep.expr}|\${ep.meaning ?? ''}';",
  );
  stdout.writeln();
  stdout.writeln('const Map<String, String> requiredProductIdByExprKey = {');
  for (final k in sortedKeys) {
    final v = entries[k]!;
    final kEsc = k.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
    final vEsc = v.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
    stdout.writeln("  '$kEsc': '$vEsc',");
  }
  stdout.writeln('};');

  if (missingRank.isNotEmpty) {
    stderr.writeln(
      'WARNING: Missing curriculum ranks for ${missingRank.length} keys (default rank=9999).',
    );
    for (final k in (missingRank..sort()).take(50)) {
      stderr.writeln('  - $k');
    }
    if (missingRank.length > 50) {
      stderr.writeln('  ... and ${missingRank.length - 50} more');
    }
  }
}

// ---------------------------------------------------------------------------
// Curriculum rank maps (copied from ProblemListPage; kept here to avoid Flutter imports)
// ---------------------------------------------------------------------------

// Mechanics ranks
const Map<String, int> _mechanicsCurriculumRank = {
  'g|重力加速度': 0,
  'x|変位': 10,
  'v|速度': 20,
  'a|加速度': 30,
  'gt|自由落下の速度': 40,
  r'\frac{1}{2}gt^2|自由落下の変位': 50,
  'm|質量': 100,
  'ma|力': 110,
  'F|力': 120,
  'mg|重力': 130,
  'N|垂直抗力': 140,
  'μ|動摩擦係数': 150,
  r'\mu N|動摩擦力': 160,
  r'\mu_{s} N|最大静止摩擦力': 170,
  r'\mu_{s} N|静止摩擦力': 180,
  'kv|空気抵抗': 190,
  'W|仕事': 200,
  'Pt|仕事': 210,
  r'\frac{1}{2}mv^2|運動エネルギー': 220,
  r'\frac{1}{2}kx^2|ばねの弾性エネルギー': 230,
  'mgh|重力の位置エネルギー': 240,
  'P|電力': 250,
  r'\frac{W}{t}|電力': 260,
  'τ|力のモーメント': 300,
  r'Fx \cos \theta|力のモーメント': 310,
  'mv|運動量': 400,
  'Ft|力積': 410,
  'e|反発係数': 420,
  'ω|角速度': 500,
  r'\omega t|角度': 510,
  r'r\omega^2|遠心力加速度': 520,
  'mrω^2|向心力': 530,
  r'\frac{mv^2}{r}|円運動の向心力': 540,
  r'\frac{mv^2}{r}|運動エネルギー': 550,
  'k|ばね定数': 600,
  'kx|ばねの力': 610,
  r'\frac{mg}{k}|ばねの平衡位置': 620,
  r'2\pi\sqrt{\frac{m}{k}}|ばね振動の周期': 630,
  r'2\pi\sqrt{\frac{l}{g}}|単振り子の周期': 640,
  'f|周波数': 650,
  r'\frac{1}{2}m\omega^2 A^2|調和振動のエネルギー': 660,
  r'\frac{F}{S}|圧力': 700,
  r'\rho h g|流体の圧力': 710,
  'ρVg|浮力': 720,
  'G|万有引力定数': 800,
  r'\frac{GMm}{r^2}|万有引力': 810,
  r'\frac{GM}{4\pi^2}|ケプラーの定数': 820,
  r'\frac{dS}{dt}|面積速度': 830,
  r'\sqrt{\frac{GM}{r}}|第一宇宙速度': 840,
  r'\sqrt{\frac{GM}{R}}|万有引力の場合の等速円運動の速度': 850,
  r'\sqrt{\frac{2GM}{r}}|第二宇宙速度': 860,
  r'-\frac{GMm}{r}|重力の位置エネルギー': 870,
};

// Electromagnetism ranks (subset sufficient for the paywall boundary logic)
// NOTE: This tool only needs ranks around capacitor block + ordering; unknown keys default to 9999.
const Map<String, int> _emCurriculumRank = {
  'k_0|クーロン定数': 10,
  'Q|電荷': 20,
  'CV|電荷': 30,
  'It|電荷': 40,
  'σ|電荷面密度': 50,
  'ε0|真空の誘電率': 60,
  'E|電場': 70,
  r'\frac{V}{\ell}|電場': 80,
  'ES|電束（電場の面積積）': 90,
  'ε0ES|電束': 100,
  r'\frac{Q}{\epsilon_0}|電束': 110,
  'V|電圧': 120,
  'Ed|起電力(電圧)': 130,
  'qEd|電場による仕事': 140,
  'C|静電容量': 200,
  r'\frac{\epsilon_0 S}{d}|静電容量': 210,
  r'\frac{Q^2}{2\epsilon_{0} S}|コンデンサ極板間引力': 220,
  r'\frac{1}{2}CV^2|静電エネルギー': 230,
  r'\frac{1}{2}QV|静電エネルギー': 240,
  r'\frac{Q^2}{2C}|静電エネルギー': 250,
  'I|電流': 300,
  r'\frac{Q}{t}|電流': 310,
  r'\frac{V}{R}|電流': 320,
  'V|電流': 330,
  'R|抵抗': 340,
  'ρ|抵抗率': 350,
  r'\frac{\rho L}{S}|抵抗': 360,
  'RI|電圧': 370,
  'VI|電力': 380,
  r'\frac{V^2}{R}|電力': 390,
  'RI^2|消費電力': 400,
  r'RI^2t|ジュール熱': 410,
  'RC|時定数': 420,
  // ... remaining entries omitted (default to 9999)
};
